### ISSUE TITLE
Importing django_sourcerer in a project

### ISSUE THREAD

**Issue by boryszef** [nokia-wroclaw/innovativeproject-django-sourcerer#5]
I am not able to import django-sourcerer in my project. Despite adding `'django_sourcerer'` to INSTALLED_APPS, I'm getting the error:

> ModuleNotFoundError: No module named 'django_sourcerer'

Please fix or add documentation how to use it.

Steps to reproduce:
```shell
git clone https://github.com/boryszef/django-sourcerer-test.git
cd django-sourcerer-test
pip install -r requirements.txt
cd sandbox
./manage.py
```

**Comment by cmarslan** [comment]
We updated the library and also added documentation. We need to update also documentation more but till now it shows what we did.

**Comment by boryszef** [comment]
It works with after the fix.
