### ISSUE TITLE
Creating models based on the yaml file

### ISSUE THREAD

**Issue by boryszef** [nokia-wroclaw/innovativeproject-django-sourcerer#6]
I have successfully imported django-sourcerer in my project:
https://github.com/boryszef/django-sourcerer-test
I have created the config file:
https://github.com/boryszef/django-sourcerer-test/blob/master/sandbox/sandbox/sourcerer.yaml
Now I would like the content of the config file to be reflected in my models. Basically, I want to be able to do this:

- my settings file contains information where the config file is located, relative to the project's root:
```python
SOURCERER_CONFIG_FILES = [
    "sandbox/sourcerer.yaml"
]
```
- when I run:
```shell
./manage.py makemigrations
```
I want django to read the config file and create migrations based on it;
- next, when I run:
```shell
./manage.py migrate
```
I want django to create models in the database
- finally, after the migrations are applied, I want to be able to do this:
```python
from django_sourcerer.models import Continents
Continents.objects.values('name', 'code')
```

**Comment by boryszef** [comment]
How to get the name(s) of the config file(s):
```python
from django.conf import settings
names = settings['SOURCERER_CONFIG_FILES']
```

**Comment by boryszef** [comment]
The best approach seems to be something like this:
first command will parse the config file and migrate the models
```python
./manage.py sourcerer_migrate
```
the second command will fetch the data and store it in the database (can be used many times)
```python
./manage.py sourcerer_update
```

**Comment by cmarslan** [comment]
Fixed issue
